Hw04 auth
Ros715/nodejs-homework-template pull request #3
Opened 2021-11-14 20:31 UTC by Ros715

2021-11-17 20:37 UTC, KirillKulakow commented on controllers/auth-ctrl.js
> +  const token = jwt.sign(payload, SECRET_KEY /*, { expiresIn: "1h" } */)
лучше не делай такие комменты внутри функций
сделай коммент отдельно

2021-11-17 20:40 UTC, KirillKulakow commented on controllers/contacts-ctrl.js
> +  const { page, limit, favorite } = req.query
а если я сделаю запрос api/contacts?page=asdawfasfc&limit=adsfgdfh
приложение сломается
исправь

2021-11-17 20:43 UTC, KirillKulakow commented on middlewares/middlewares.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
если я буду не авторизированный и попытаюсь взять список контактов - получу ошибку из этой строки

2021-11-17 20:44 UTC, KirillKulakow commented on middlewares/middlewares.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
необработаную (со статусом 500)

2021-11-17 20:44 UTC, KirillKulakow commented on middlewares/middlewares.js
> +        throw new NotFound('User not found')
почему ты здесь пишешь ошибку notFound если в catch ты тип ошибки перезаписываешь?

2021-11-17 20:46 UTC, KirillKulakow requested changes
need fix

2021-11-17 22:14 UTC, Ros715 commented on controllers/auth-ctrl.js
> +  const token = jwt.sign(payload, SECRET_KEY /*, { expiresIn: "1h" } */)
done

2021-11-17 22:15 UTC, Ros715 commented on controllers/contacts-ctrl.js
> +  const { page, limit, favorite } = req.query
done

2021-11-17 22:43 UTC, Ros715 commented on middlewares/middlewares.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
done

2021-11-17 22:44 UTC, Ros715 commented on middlewares/middlewares.js
> +        throw new NotFound('User not found')
done

2021-11-18 18:39 UTC, KirillKulakow approved these changes

2021-11-20 20:47 UTC, merged