Hw05 avatar
Ros715/nodejs-homework-template pull request #4
Opened 2021-11-22 23:48 UTC by Ros715

2021-11-23 19:45 UTC, KirillKulakow commented on controllers/auth-ctrl.js
> +// const { v4 } = require("uuid");
это. удалить

2021-11-23 19:47 UTC, KirillKulakow commented on controllers/auth-ctrl.js
> +    // await fs.rename(tempUpload, resultUpload);
удалить

2021-11-23 19:48 UTC, KirillKulakow commented on middlewares/uploadMiddleware.js
> +  filename: (req, file, cb) => {
было бы неплохо сделать проверку на MIME тип

2021-11-23 19:48 UTC, KirillKulakow commented on model/user.js
> +  this.avatarURL = gravatar.url(email)
здесь можно добавить опцию http протокол

2021-11-23 19:48 UTC, KirillKulakow requested changes
need some fix

2021-11-23 20:53 UTC, Ros715 commented on controllers/auth-ctrl.js
> +// const { v4 } = require("uuid");
done

2021-11-23 20:54 UTC, Ros715 commented on controllers/auth-ctrl.js
> +    // await fs.rename(tempUpload, resultUpload);
done

2021-11-23 21:52 UTC, Ros715 commented on model/user.js
> +  this.avatarURL = gravatar.url(email)
done

2021-11-23 22:30 UTC, Ros715 commented on middlewares/uploadMiddleware.js
> +  filename: (req, file, cb) => {
done

2021-11-24 20:27 UTC, KirillKulakow approved these changes

2021-11-24 23:30 UTC, merged